### ISSUE TITLE
Malayalam Translation Progress

### ISSUE THREAD

**Issue by tesseralis** [reactjs/ml.reactjs.org#1]
## Maintainer list
* @shahulhameed00 
* @stultus 

## For New Translators

To translate a page:

1. Check that no one else has claimed your page in the checklist and comments below.
2. Comment below with the name of the page you would like to translate. **Take only one page at a time**.
3. Clone this repo, translate your page, and submit a pull request!

Before contributing, read the glossary and style guide (once they exist) to understand how to translate various technical and React-specific terms.

Please be prompt with your translations! If you find find that you can't commit any more, let the maintainers know so they can assign the page to someone else.

## For maintainers

When someone volunteers, edit this issue with the username of the volunteer, and with the PR. Ex:

* [ ] Home Page (@tesseralis) #10 

When PRs are merged, make sure to mark that page as completed!

## Core Pages

To do before releasing as an "official" translation. **Please translate these pages first.**

* [x] Home Page (@shahulhameed00) #10 
* [ ] Tutorial

### Basics

* [x] Hello World (@BoyWithSilverWings )
* [ ] Introducing JSX (@Farzanfa)
* [ ] Rendering Elements (@robintom)
* [ ] Components and Props
* [ ] State and Lifecycle
* [ ] Handling Events (@vineeth-nair)
* [ ] Conditional Rendering
* [ ] Lists and Keys
* [x] Forms (@jomonthomaslobo )
* [ ] Lifting State Up
* [ ] Composition vs Inheritance
* [ ] Thinking in React

### API Reference

* [ ] React
* [ ] React.Component
* [ ] ReactDOM
* [ ] ReactDOMServer
* [ ] DOM Elements
* [ ] SyntheticEvent
* [ ] Test Utilities
* [ ] Shallow Renderer
* [ ] Test Renderer
* [ ] JS Environment Requirements
* [ ] Glossary

### Navigation

These are the navigation links that appears in the sidebar. Possibly wait until
the corresponding sections are translated to do these.

* [ ] tutorial/nav.yml
* [ ] docs/nav.yml

## Next Steps

These are the next most important translations, ordered by importance:

### Installation

* [ ] Getting Started (@kurianbenoy)
* [ ] Add React to a Website
* [ ] Create a New React App
* [ ] CDN Links

### Hooks

Everyone is hooked on hooks! People are really excited for these and it would be great for them to be translated.

  * [x] Introducing Hooks (@BoyWithSilverWings)
  * [ ] Hooks at a Glance (@BoyWithSilverWings)
  * [ ] Using the State Hook
  * [ ] Using the Effect Hook
  * [ ] Rules of Hooks
  * [ ] Building Your Own Hooks
  * [ ] Hooks API Reference
  * [ ] Hooks FAQ

### Warnings

These are the pages that you get when you click the links in the console (e.g. https://reactjs.org/warnings/dont-call-proptypes.html). People tend to search these, so **please don't translate the error message itself**.
 
* [ ] dont-call-proptypes
* [ ] invalid-aria-prop
* [ ] invalid-hook-call-warning
* [ ] legacy-factories
* [ ] refs-must-have-owner
* [ ] special-props
* [ ] unknown-prop

### Advanced Guides

* [ ] Accessibility
* [ ] Code-Splitting
* [ ] Context
* [ ] Error Boundaries
* [ ] Forwarding Refs
* [ ] Fragments
* [ ] Higher-Order Components
* [ ] Integrating with Other Libraries
* [ ] JSX In Depth
* [ ] Optimizing Performance
* [ ] Portals
* [ ] React Without ES6
* [ ] React Without JSX
* [ ] Reconciliation
* [ ] Refs and the DOM
* [ ] Render Props
* [ ] Static Type Checking
* [ ] Strict Mode
* [ ] Typechecking With PropTypes
* [ ] Uncontrolled Components
* [ ] Web Components

### FAQ

* [ ] APIs and AJAX
* [ ] Babel, JSX, and Build Steps
* [ ] Passing Functions to Components
* [ ] Component State
* [ ] Styling and CSS
* [ ] File Structure
* [ ] Versioning Policy
* [ ] Virtual DOM and Internals

### Contributing

Priority: Low

* [ ] How to Contribute
* [ ] Codebase Overview
* [ ] Implementation Notes
* [ ] Design Principles

### Components

Components in `src/components` that have some text in them.

* [ ] CodeEditor
* [ ] CodeExample
* [ ] ErrorDecoder
* [ ] LayoutFooter
* [ ] LayoutHeader
* [ ] MarkdownPage

## Additional Translations

These are not the primary translation targets.

* [ ] Blog
* [ ] Community

**Comment by tesseralis** [comment]
@shahulhameed00 @stultus use this issue to keep track of translation progress!

**Comment by tesseralis** [comment]
Hi @shahulhameed00 and @stultus, how are things going? Please let me know if you need any help or if you have any questions.

**Comment by shahulhameed00** [comment]
@tesseralis We are just getting started and expect to complete few pages by end of this week. We have also reached out to a couple of others to become contributors. Hoping for the best 👍

**Comment by tesseralis** [comment]
Hey @shahulhameed00, how's it going?

Also, @stultus, could you accept the invitation to join the reactjs github organization so you can get admin access to the repo? Let me know if you can't find it and I can resend the invite.

**Comment by stultus** [comment]
@tesseralis Done.  Thanks for the invitation :)

**Comment by BoyWithSilverWings** [comment]
I'm picking up Hello World page

**Comment by jomonthomaslobo** [comment]
I am on forms.md

**Comment by Farzanfa** [comment]
I am doing Introducing JSX

**Comment by vineeth-nair** [comment]
I'm picking up Handling events

**Comment by BoyWithSilverWings** [comment]
Picking up **Introducing Hooks** next

**Comment by shahulhameed00** [comment]
@Farzanfa @vineeth-nair Thanks for your interest. Let us know if you are stuck somewhere.

**Comment by BoyWithSilverWings** [comment]
Picking up **Hooks at a Glance**

**Comment by robintom** [comment]
@shahulhameed00 @stultus I would love to be part of this. Can i jump in ?

Just need some basic walk-through on what Malayalam font or what process you guys use.

**Comment by stultus** [comment]
@robintom You don't have to worry about the font.  As long as you are inputting unicode text we are good to go :)

**Comment by jomonthomaslobo** [comment]
my PR is open

**Comment by stultus** [comment]
Will look into it tonight @jomonthomaslobo

**Comment by jomonthomaslobo** [comment]
@stultus  Let me know any corrections

**Comment by stultus** [comment]
@jomonthomaslobo I've made some comments

**Comment by jomonthomaslobo** [comment]
thanks for the feedback imporve

**Comment by kurianbenoy** [comment]
@shahulhameed00 @stultus can I work on **Installation:Getting Started** page?

**Comment by tesseralis** [comment]
@kurianbenoy @BoyWithSilverWings @vineeth-nair I updated the issue to reflect the pages you asked for!

@robintom I gave you **Rendering Elements** for now. Please let me know if you have any questions about the process/GitHub.

@shahulhameed00 @stultus , could you make sure to keep this issue updated?

**Comment by shahulhameed00** [comment]
@tesseralis Yeah, sure.

**Comment by kurianbenoy** [comment]
@shahulhameed00 and @stultus can you recommend me a way to type in malayalam properly, which is friendly even for a beginner like me. I have started working on issue, but this tweet https://twitter.com/Daminisatya/status/1111612137028222982 changed me to stop current way of doing translation

**Comment by stultus** [comment]
There are many tools like swanalekha, (http://swanalekha.smc.org.in/) varnam (https://www.varnamproject.com/editor) etc to type malayalam.  Don't use google translate.  
read each sentence and understand it. then write as if you are explaining it (without losing any points) to a friend in malayalam.

**Comment by adityarpai843** [comment]
@shahulhameed00 @stultus i want to work in transalation project i've done localisation of KDE.So which page should i  start

**Comment by abidhkm** [comment]
picking up "Rules of Hooks"

**Comment by sinumohan** [comment]
@shahulhameed00 @stultus  Can I work on the State and Lifecycle page?

**Comment by shahulhameed00** [comment]
> @shahulhameed00 @stultus Can I work on the State and Lifecycle page?

Yes, please. Make the necessary changes and submit a PR.

**Comment by kidilowski** [comment]
Hey, I'm starting to work on the **Thinking in React** page!

**Comment by bharadhwaj** [comment]
@stultus @shahulhameed00 Planning to start working on **Conditional Rendering**. Hope nobody is working on it looking at the thread.

**Comment by renjithspace** [comment]
@tesseralis @stultus @shahulhameed00 I've created a PR #82. Anyone here to review that? I'm new here. I can see a few more PRs pending since this year. I'd like to continue translation on other pages if the repo is actively maintaining. Thanks!

**Comment by shahulhameed00** [comment]
> @tesseralis @stultus @shahulhameed00 I've created a PR #82. Anyone here to review that? I'm new here. I can see a few more PRs pending since this year. I'd like to continue translation on other pages if the repo is actively maintaining. Thanks!
I've reviewed your commits and added comments. Please go through the same fix and submit PR.

**Comment by httpanand** [comment]
Is this project completed  @tesseralis  ?  If not can i join in for translation ?

**Comment by dev-thakku** [comment]
@theshahulhameed @stultus I would like to work on the `State and Lifecycle` page.

**Comment by gaearon** [comment]
It looks like this translation has stalled, and is now very outdated.
I'm going to archive this repo, but if someone wants to pick up, please start a new effort.
